active_group:  # 此项下为要生效的群组，清空即为所有群组都生效
# - 123456789
# - 012345678

normal:  # 此项下的内容会回复纯文本
  此处填关键词: 此处填要回复的内容

with_img:  # 此项下的内容会生成图片来回复
  此处填关键词1: 此处填要回复的内容
  此处填关键词2: |-
    此处填要回复的内容
    多行这样写噢，注意前面的空格
    实在不行用换行符也行

text_to_img:  # 此项为文字生成图片相关
  font_name: OPPOSans.ttf  # 字体文件的文件名（带后缀名），支持ttf/otf/ttc/otc
  font_size: 30  # 字体大小
  font_color: '#0E0E0E'  # 字体颜色，示例【#000000】
  line_space: 10  # 行间距
  left_margin: 60  # 左间距
  right_margin: 60  # 右间距
  top_margin: 90  # 上间距
  bottom_margin: 90  # 下间距
